const artists = [
  { id: 'beatles', name: 'The Beatles', type: 'band', country: 'UK', activeSince: 1960, activeUntil: 1970 },
  { id: 'pink-floyd', name: 'Pink Floyd', type: 'band', country: 'UK', activeSince: 1965, activeUntil: null },
  { id: 'michael-jackson', name: 'Michael Jackson', type: 'solo', country: 'US', activeSince: 1964, activeUntil: 2009 },
  { id: 'led-zeppelin', name: 'Led Zeppelin', type: 'band', country: 'UK', activeSince: 1968, activeUntil: 1980 },
  { id: 'nirvana', name: 'Nirvana', type: 'band', country: 'US', activeSince: 1987, activeUntil: 1994 },
  { id: 'radiohead', name: 'Radiohead', type: 'band', country: 'UK', activeSince: 1985, activeUntil: null },
  { id: 'queen', name: 'Queen', type: 'band', country: 'UK', activeSince: 1970, activeUntil: null },
  { id: 'david-bowie', name: 'David Bowie', type: 'solo', country: 'UK', activeSince: 1967, activeUntil: 2016 },
  { id: 'fleetwood-mac', name: 'Fleetwood Mac', type: 'band', country: 'UK/US', activeSince: 1967, activeUntil: null },
  { id: 'metallica', name: 'Metallica', type: 'band', country: 'US', activeSince: 1981, activeUntil: null },
  { id: 'beach-boys', name: 'The Beach Boys', type: 'band', country: 'US', activeSince: 1961, activeUntil: null },
  { id: 'acdc', name: 'AC/DC', type: 'band', country: 'Australia', activeSince: 1973, activeUntil: null }
];

const records = [
  // 1–2. Abbey Road — два видання
  { 
    id: 'abbey-road-1969-UK-1st', 
    masterId: 'abbey-road-1969', 
    title: 'Abbey Road', 
    artistIds: ['beatles'], 
    year: 1969, 
    pressingYear: 1969, 
    label: 'Apple Records', 
    catalogNumber: 'PCS 7088', 
    matrixNumberSideA: 'YEX 749-2', 
    matrixNumberSideB: 'YEX 750-1', 
    country: 'UK', 
    format: 'LP', 
    condition: 'Near Mint', 
    price: 189.00, 
    genres: ['Rock', 'Pop'], 
    recordingInfo: {studio: 'Abbey Road Studios', producer: 'George Martin', engineer: 'Geoff Emerick', recordingDates: 'Feb–Aug 1969'}, 
    tracklist: [{n:1,t:'Come Together',d:'4:20'},{n:2,t:'Something',d:'3:03'},{n:3,t:'Maxwell\'s Silver Hammer',d:'3:27'}], 
    description: 'Останній записаний альбом The Beatles', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'abbey-road-1987-JP', 
    masterId: 'abbey-road-1969', 
    title: 'Abbey Road (Remaster)', 
    artistIds: ['beatles'], 
    year: 1969, 
    pressingYear: 1987, 
    label: 'Toshiba-EMI', 
    catalogNumber: 'TOJP-60139', 
    matrixNumberSideA: 'YEX 749-2', 
    matrixNumberSideB: 'YEX 750-1', 
    country: 'Japan', 
    format: 'LP', 
    condition: 'Mint', 
    price: 78.50, 
    genres: ['Rock', 'Pop'], 
    recordingInfo: {studio: 'Abbey Road Studios', producer: 'George Martin', engineer: 'Geoff Emerick', recordingDates: 'Feb–Aug 1969'}, 
    tracklist: [{n:1,t:'Come Together',d:'4:20'},{n:2,t:'Something',d:'3:03'}], 
    description: 'Японський ремастер оригінального мастерингу', 
    coverUrl: 'images/covers/covers.jpg' 
  },

  // 3–4. Dark Side of the Moon — два видання
  { 
    id: 'dark-side-1973-UK-1st', 
    masterId: 'dark-side-1973', 
    title: 'The Dark Side of the Moon', 
    artistIds: ['pink-floyd'], 
    year: 1973, 
    pressingYear: 1973, 
    label: 'Harvest', 
    catalogNumber: 'SHVL 804', 
    matrixNumberSideA: 'SHVL 804 A-2U', 
    matrixNumberSideB: 'SHVL 804 B-3U', 
    country: 'UK', 
    format: 'LP', 
    condition: 'VG+', 
    price: 145.00, 
    genres: ['Progressive Rock'], 
    recordingInfo: {studio: 'Abbey Road', producer: 'Pink Floyd', engineer: 'Alan Parsons', recordingDates: '1972–1973'}, 
    tracklist: [{n:1,t:'Speak to Me',d:'1:30'},{n:2,t:'Breathe',d:'2:43'},{n:3,t:'Time',d:'7:04'}], 
    description: 'Найвпливовіший концептуальний альбом', 
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png' 
  },
  { 
    id: 'dark-side-1973-US-30th', 
    masterId: 'dark-side-1973', 
    title: 'The Dark Side of the Moon (30th Anniv)', 
    artistIds: ['pink-floyd'], 
    year: 1973, 
    pressingYear: 2003, 
    label: 'Capitol', 
    catalogNumber: '7243 5 82136 1 2', 
    matrixNumberSideA: 'SHVL 804 A-2U', 
    matrixNumberSideB: 'SHVL 804 B-3U', 
    country: 'US', 
    format: 'LP', 
    condition: 'Near Mint', 
    price: 92.00, 
    genres: ['Progressive Rock'], 
    recordingInfo: {studio: 'Abbey Road', producer: 'Pink Floyd', engineer: 'Alan Parsons', recordingDates: '1972–1973'}, 
    tracklist: [{n:1,t:'Speak to Me',d:'1:30'},{n:2,t:'Breathe',d:'2:43'}], 
    description: 'Американське ювілейне видання', 
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png' 
  },

  // 5. Thriller
  { 
    id: 'thriller-1982-US-1st', 
    masterId: 'thriller-1982', 
    title: 'Thriller', 
    artistIds: ['michael-jackson'], 
    year: 1982, 
    pressingYear: 1982, 
    label: 'Epic', 
    catalogNumber: 'QE 38112', 
    matrixNumberSideA: 'AL 38112-1A', 
    matrixNumberSideB: 'BL 38112-1B', 
    country: 'US', 
    format: 'LP', 
    condition: 'Near Mint', 
    price: 65.00, 
    genres: ['Pop', 'R&B'], 
    recordingInfo: {studio: 'Westlake', producer: 'Quincy Jones', engineer: 'Bruce Swedien', recordingDates: '1982'}, 
    tracklist: [{n:1,t:'Wanna Be Startin\' Somethin\'',d:'6:03'},{n:2,t:'Thriller',d:'5:57'}], 
    description: 'Найпродаваніший альбом в історії', 
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png' 
  },

  // 6–7. Led Zeppelin IV — два видання
  { 
    id: 'led-zeppelin-iv-1971-UK-1st', 
    masterId: 'led-zeppelin-iv-1971', 
    title: 'Led Zeppelin IV', 
    artistIds: ['led-zeppelin'], 
    year: 1971, 
    pressingYear: 1971, 
    label: 'Atlantic', 
    catalogNumber: 'K 78121', 
    matrixNumberSideA: 'K 78121 A1', 
    matrixNumberSideB: 'K 78121 B2', 
    country: 'UK', 
    format: 'LP', 
    condition: 'VG', 
    price: 195.00, 
    genres: ['Hard Rock'], 
    recordingInfo: {studio: 'Headley Grange', producer: 'Jimmy Page', engineer: 'Andy Johns', recordingDates: '1971'}, 
    tracklist: [{n:1,t:'Black Dog',d:'4:54'},{n:4,t:'Stairway to Heaven',d:'8:02'}], 
    description: 'Легендарний альбом з "Stairway to Heaven"', 
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/2/26/Led_Zeppelin_-_Led_Zeppelin_IV.jpg' 
  },
  { 
    id: 'led-zeppelin-iv-1971-US-2nd', 
    masterId: 'led-zeppelin-iv-1971', 
    title: 'Led Zeppelin IV', 
    artistIds: ['led-zeppelin'], 
    year: 1971, 
    pressingYear: 1972, 
    label: 'Atlantic', 
    catalogNumber: 'SD 19129', 
    matrixNumberSideA: 'K 78121 A1', 
    matrixNumberSideB: 'K 78121 B2', 
    country: 'US', 
    format: 'LP', 
    condition: 'Good', 
    price: 85.00, 
    genres: ['Hard Rock'], 
    recordingInfo: {studio: 'Headley Grange', producer: 'Jimmy Page', engineer: 'Andy Johns', recordingDates: '1971'}, 
    tracklist: [{n:1,t:'Black Dog',d:'4:54'},{n:4,t:'Stairway to Heaven',d:'8:02'}], 
    description: 'Ранній американський прес', 
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/2/26/Led_Zeppelin_-_Led_Zeppelin_IV.jpg' 
  },

  // 8. Nevermind
  { 
    id: 'nevermind-1991-US-1st', 
    masterId: 'nevermind-1991', 
    title: 'Nevermind', 
    artistIds: ['nirvana'], 
    year: 1991, 
    pressingYear: 1991, 
    label: 'DGC', 
    catalogNumber: 'DGC-24425', 
    matrixNumberSideA: 'DGC-24425-A', 
    matrixNumberSideB: 'DGC-24425-B', 
    country: 'US', 
    format: 'LP', 
    condition: 'VG+', 
    price: 120.00, 
    genres: ['Grunge'], 
    recordingInfo: {studio: 'Sound City, Van Nuys', producer: 'Butch Vig', engineer: 'Andy Wallace', recordingDates: 'May–June 1991'}, 
    tracklist: [{n:1,t:'Smells Like Teen Spirit',d:'5:01'},{n:2,t:'Come As You Are',d:'3:39'}], 
    description: 'Альбом, що змінив рок-музику 90-х', 
    coverUrl: 'images/covers/covers.jpg' 
  },

  // 9. OK Computer
  { 
    id: 'ok-computer-1997-UK-1st', 
    masterId: 'ok-computer-1997', 
    title: 'OK Computer', 
    artistIds: ['radiohead'], 
    year: 1997, 
    pressingYear: 1997, 
    label: 'Parlophone', 
    catalogNumber: 'PCX 7375', 
    matrixNumberSideA: 'PCX 7375 A-1-1-1', 
    matrixNumberSideB: 'PCX 7375 B-1-1-1', 
    country: 'UK', 
    format: 'LP', 
    condition: 'Near Mint', 
    price: 140.00, 
    genres: ['Alternative Rock'], 
    recordingInfo: {studio: 'Canned Applause & St Catherine’s Court', producer: 'Nigel Godrich', engineer: 'Nigel Godrich', recordingDates: '1996–1997'}, 
    tracklist: [{n:1,t:'Airbag',d:'4:44'},{n:2,t:'Paranoid Android',d:'6:23'}], 
    description: 'Шедевр альтернативного року кінця 90-х', 
    coverUrl: 'images/covers/covers.jpg' 
  },

  // 10. A Night at the Opera
  { 
    id: 'night-at-opera-1975-UK-1st', 
    masterId: 'night-at-opera-1975', 
    title: 'A Night at the Opera', 
    artistIds: ['queen'], 
    year: 1975, 
    pressingYear: 1975, 
    label: 'EMI', 
    catalogNumber: 'EMD 7509', 
    matrixNumberSideA: 'EMD 7509 A-1', 
    matrixNumberSideB: 'EMD 7509 B-2', 
    country: 'UK', 
    format: 'LP', 
    condition: 'VG', 
    price: 110.00, 
    genres: ['Rock'], 
    recordingInfo: {studio: 'Various (Sarm, Scorpio, Roundhouse etc.)', producer: 'Roy Thomas Baker & Queen', engineer: 'Mike Stone', recordingDates: '1975'}, 
    tracklist: [{n:1,t:'Death on Two Legs',d:'3:43'},{n:11,t:'Bohemian Rhapsody',d:'5:55'}], 
    description: 'Альбом з легендарним "Bohemian Rhapsody"', 
    coverUrl: 'images/covers/covers.jpg' 
  },

  // 11. Rumours
  { 
    id: 'rumours-1977-US-1st', 
    masterId: 'rumours-1977', 
    title: 'Rumours', 
    artistIds: ['fleetwood-mac'], 
    year: 1977, 
    pressingYear: 1977, 
    label: 'Warner Bros.', 
    catalogNumber: 'BSK 3010', 
    matrixNumberSideA: 'BSK 3010-A', 
    matrixNumberSideB: 'BSK 3010-B', 
    country: 'US', 
    format: 'LP', 
    condition: 'Near Mint', 
    price: 75.00, 
    genres: ['Soft Rock', 'Pop'], 
    recordingInfo: {studio: 'Record Plant, Sausalito', producer: 'Fleetwood Mac & Richard Dashut & Ken Caillat', engineer: 'Ken Caillat', recordingDates: '1976–1977'}, 
    tracklist: [{n:1,t:'Second Hand News',d:'2:43'},{n:2,t:'Dreams',d:'4:18'}], 
    description: 'Один з найпродаваніших альбомів усіх часів', 
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fb/FMacRumours.PNG' 
  },

  // 12. Ziggy Stardust
  { 
    id: 'ziggy-stardust-1972-UK-1st', 
    masterId: 'ziggy-stardust-1972', 
    title: 'The Rise and Fall of Ziggy Stardust...', 
    artistIds: ['david-bowie'], 
    year: 1972, 
    pressingYear: 1972, 
    label: 'RCA Victor', 
    catalogNumber: 'SF 8287', 
    matrixNumberSideA: 'SF 8287 A-2U', 
    matrixNumberSideB: 'SF 8287 B-3U', 
    country: 'UK', 
    format: 'LP', 
    condition: 'VG+', 
    price: 160.00, 
    genres: ['Glam Rock'], 
    recordingInfo: {studio: 'Trident Studios, London', producer: 'Ken Scott & David Bowie', engineer: 'Ken Scott', recordingDates: '1971–1972'}, 
    tracklist: [{n:1,t:'Five Years',d:'4:43'},{n:5,t:'Starman',d:'4:13'}], 
    description: 'Культовий концептуальний альбом Bowie', 
    coverUrl: 'images/covers/covers.jpg' 
  },

  // 13–20 — короткі приклади з обкладинками
  { 
    id: 'master-of-puppets-1986-US-1st', 
    masterId: 'master-of-puppets-1986', 
    title: 'Master of Puppets', 
    artistIds: ['metallica'], 
    year: 1986, 
    pressingYear: 1986, 
    label: 'Elektra', 
    catalogNumber: '60439-1', 
    matrixNumberSideA: '60439-A', 
    matrixNumberSideB: '60439-B', 
    country: 'US', 
    format: 'LP', 
    condition: 'VG+', 
    price: 130.00, 
    genres: ['Thrash Metal'], 
    description: 'Шедевр треш-металу', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'master-of-puppets-1986-GER', 
    masterId: 'master-of-puppets-1986', 
    title: 'Master of Puppets', 
    artistIds: ['metallica'], 
    year: 1986, 
    pressingYear: 1986, 
    label: 'Vertigo', 
    catalogNumber: '838 141-1', 
    matrixNumberSideA: '60439-A', 
    matrixNumberSideB: '60439-B', 
    country: 'Germany', 
    format: 'LP', 
    condition: 'Near Mint', 
    price: 95.00, 
    genres: ['Thrash Metal'], 
    description: 'Німецьке видання класики Metallica', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'in-utero-1993-US-1st', 
    masterId: 'in-utero-1993', 
    title: 'In Utero', 
    artistIds: ['nirvana'], 
    year: 1993, 
    pressingYear: 1993, 
    label: 'DGC', 
    catalogNumber: 'DGC-24607', 
    matrixNumberSideA: 'DGC-24607-A', 
    matrixNumberSideB: 'DGC-24607-B', 
    country: 'US', 
    format: 'LP', 
    condition: 'VG', 
    price: 110.00, 
    genres: ['Grunge'], 
    description: 'Останній студійний альбом Nirvana', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'kid-a-2000-UK-1st', 
    masterId: 'kid-a-2000', 
    title: 'Kid A', 
    artistIds: ['radiohead'], 
    year: 2000, 
    pressingYear: 2000, 
    label: 'Parlophone', 
    catalogNumber: 'XLLP 782', 
    matrixNumberSideA: 'XLLP 782 A-1', 
    matrixNumberSideB: 'XLLP 782 B-1', 
    country: 'UK', 
    format: '2LP', 
    condition: 'Mint', 
    price: 85.00, 
    genres: ['Electronic', 'Experimental'], 
    description: 'Революційний електронний поворот Radiohead', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'nevermind-1991-EU-2nd', 
    masterId: 'nevermind-1991', 
    title: 'Nevermind', 
    artistIds: ['nirvana'], 
    year: 1991, 
    pressingYear: 1992, 
    label: 'Geffen', 
    catalogNumber: '0720642452511', 
    matrixNumberSideA: 'DGC-24425-A', 
    matrixNumberSideB: 'DGC-24425-B', 
    country: 'EU', 
    format: 'LP', 
    condition: 'VG+', 
    price: 70.00, 
    genres: ['Grunge'], 
    description: 'Європейське видання 1992 року', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'pet-sounds-1966-US-1st', 
    masterId: 'pet-sounds-1966', 
    title: 'Pet Sounds', 
    artistIds: ['beach-boys'], 
    year: 1966, 
    pressingYear: 1966, 
    label: 'Capitol', 
    catalogNumber: 'T 2354', 
    matrixNumberSideA: 'T1-2354-A', 
    matrixNumberSideB: 'T1-2354-B', 
    country: 'US', 
    format: 'LP', 
    condition: 'VG', 
    price: 220.00, 
    genres: ['Baroque Pop'], 
    description: 'Шедевр Браяна Вілсона', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'back-in-black-1980-UK-1st', 
    masterId: 'back-in-black-1980', 
    title: 'Back in Black', 
    artistIds: ['acdc'], 
    year: 1980, 
    pressingYear: 1980, 
    label: 'Albert Productions', 
    catalogNumber: 'AP-3000', 
    matrixNumberSideA: 'AP-3000-A', 
    matrixNumberSideB: 'AP-3000-B', 
    country: 'Australia', 
    format: 'LP', 
    condition: 'Near Mint', 
    price: 95.00, 
    genres: ['Hard Rock'], 
    description: 'Найпродаваніший хард-рок альбом', 
    coverUrl: 'images/covers/covers.jpg' 
  },
  { 
    id: 'back-in-black-1980-US', 
    masterId: 'back-in-black-1980', 
    title: 'Back in Black', 
    artistIds: ['acdc'], 
    year: 1980, 
    pressingYear: 1980, 
    label: 'Atlantic', 
    catalogNumber: 'SD 16018', 
    matrixNumberSideA: 'ST-A-80455-SP', 
    matrixNumberSideB: 'ST-A-80456-SP', 
    country: 'US', 
    format: 'LP', 
    condition: 'VG+', 
    price: 80.00, 
    genres: ['Hard Rock'], 
    description: 'Американський оригінальний прес', 
    coverUrl: 'images/covers/covers.jpg' 
  }
];

// Глобальні змінні для доступу з інших скриптів
window.artists = artists;
window.records = records;
